"""add_defense_and_team_stats

Revision ID: 3dd04e7fdf37
Revises: e9f037625a31
Create Date: 2025-11-18 20:35:59.253281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd04e7fdf37'
down_revision = 'e9f037625a31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_defense_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('solo_tackle', sa.Integer(), nullable=True),
    sa.Column('assist_tackle', sa.Integer(), nullable=True),
    sa.Column('sacks', sa.Float(), nullable=True),
    sa.Column('qb_hits', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('pass_defended', sa.Integer(), nullable=True),
    sa.Column('fumbles_forced', sa.Integer(), nullable=True),
    sa.Column('fumbles_recovered', sa.Integer(), nullable=True),
    sa.Column('defensive_tds', sa.Integer(), nullable=True),
    sa.Column('safeties', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_standard', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_defense_stats_id'), 'player_game_defense_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_game_defense_stats_season'), 'player_game_defense_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_game_defense_stats_team'), 'player_game_defense_stats', ['team'], unique=False)
    op.create_index(op.f('ix_player_game_defense_stats_week'), 'player_game_defense_stats', ['week'], unique=False)
    op.create_table('team_game_defense_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('points_allowed', sa.Integer(), nullable=True),
    sa.Column('yards_allowed', sa.Float(), nullable=True),
    sa.Column('sacks', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('fumbles_recovered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_game_defense_stats_id'), 'team_game_defense_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_game_defense_stats_season'), 'team_game_defense_stats', ['season'], unique=False)
    op.create_index(op.f('ix_team_game_defense_stats_team_name'), 'team_game_defense_stats', ['team_name'], unique=False)
    op.create_index(op.f('ix_team_game_defense_stats_week'), 'team_game_defense_stats', ['week'], unique=False)
    op.create_table('team_game_offense_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('total_yards', sa.Float(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_game_offense_stats_id'), 'team_game_offense_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_game_offense_stats_season'), 'team_game_offense_stats', ['season'], unique=False)
    op.create_index(op.f('ix_team_game_offense_stats_team_name'), 'team_game_offense_stats', ['team_name'], unique=False)
    op.create_index(op.f('ix_team_game_offense_stats_week'), 'team_game_offense_stats', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_game_offense_stats_week'), table_name='team_game_offense_stats')
    op.drop_index(op.f('ix_team_game_offense_stats_team_name'), table_name='team_game_offense_stats')
    op.drop_index(op.f('ix_team_game_offense_stats_season'), table_name='team_game_offense_stats')
    op.drop_index(op.f('ix_team_game_offense_stats_id'), table_name='team_game_offense_stats')
    op.drop_table('team_game_offense_stats')
    op.drop_index(op.f('ix_team_game_defense_stats_week'), table_name='team_game_defense_stats')
    op.drop_index(op.f('ix_team_game_defense_stats_team_name'), table_name='team_game_defense_stats')
    op.drop_index(op.f('ix_team_game_defense_stats_season'), table_name='team_game_defense_stats')
    op.drop_index(op.f('ix_team_game_defense_stats_id'), table_name='team_game_defense_stats')
    op.drop_table('team_game_defense_stats')
    op.drop_index(op.f('ix_player_game_defense_stats_week'), table_name='player_game_defense_stats')
    op.drop_index(op.f('ix_player_game_defense_stats_team'), table_name='player_game_defense_stats')
    op.drop_index(op.f('ix_player_game_defense_stats_season'), table_name='player_game_defense_stats')
    op.drop_index(op.f('ix_player_game_defense_stats_id'), table_name='player_game_defense_stats')
    op.drop_table('player_game_defense_stats')
    # ### end Alembic commands ###
