"""Add humidity and PlayerSeasonStats

Revision ID: 43b63420d188
Revises: dd3c78412bbc
Create Date: 2025-11-19 23:17:52.846804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b63420d188'
down_revision = 'dd3c78412bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_half_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('ppg_half_ppr', sa.Float(), nullable=True),
    sa.Column('vorp', sa.Float(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('passing_tds', sa.Integer(), nullable=True),
    sa.Column('passing_int', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_tds', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Float(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('fumbles_lost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_season_stats_id'), 'player_season_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_season_stats_season'), 'player_season_stats', ['season'], unique=False)
    op.add_column('games', sa.Column('forecast_humidity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'forecast_humidity')
    op.drop_index(op.f('ix_player_season_stats_season'), table_name='player_season_stats')
    op.drop_index(op.f('ix_player_season_stats_id'), table_name='player_season_stats')
    op.drop_table('player_season_stats')
    # ### end Alembic commands ###
