"""add_status_to_player_game_stats

Revision ID: 5f17014fad64
Revises: 1ecfa52197b2
Create Date: 2025-11-21 15:21:46.485209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f17014fad64'
down_revision = '1ecfa52197b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_depth_charts_id'), 'depth_charts', ['id'], unique=False)
    op.add_column('player_game_stats', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game_stats', 'status')
    op.drop_index(op.f('ix_depth_charts_id'), table_name='depth_charts')
    # ### end Alembic commands ###
