"""add_attempts_to_team_stats

Revision ID: a17ee946a36f
Revises: 3dd04e7fdf37
Create Date: 2025-11-18 21:26:36.224287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17ee946a36f'
down_revision = '3dd04e7fdf37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_offense_stats', sa.Column('pass_attempts', sa.Integer(), nullable=True))
    op.add_column('team_game_offense_stats', sa.Column('rush_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_offense_stats', 'rush_attempts')
    op.drop_column('team_game_offense_stats', 'pass_attempts')
    # ### end Alembic commands ###
