"""Add weather fields to Game

Revision ID: dd3c78412bbc
Revises: f5ee7d8d9278
Create Date: 2025-11-19 22:58:47.706665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3c78412bbc'
down_revision = 'f5ee7d8d9278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('forecast_wind_speed', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('forecast_temp_low', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('forecast_temp_high', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('forecast_description', sa.String(), nullable=True))
    op.add_column('games', sa.Column('stadium_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'stadium_details')
    op.drop_column('games', 'forecast_description')
    op.drop_column('games', 'forecast_temp_high')
    op.drop_column('games', 'forecast_temp_low')
    op.drop_column('games', 'forecast_wind_speed')
    # ### end Alembic commands ###
