"""add_player_game_stats

Revision ID: e9f037625a31
Revises: 001_initial_schema
Create Date: 2025-11-18 20:00:16.272243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f037625a31'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('pass_attempts', sa.Integer(), nullable=True),
    sa.Column('pass_completions', sa.Integer(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('passing_tds', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('rush_attempts', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_tds', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Float(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_standard', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_stats_id'), 'player_game_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_season'), 'player_game_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_game_stats_team'), 'player_game_stats', ['team'], unique=False)
    op.create_index(op.f('ix_player_game_stats_week'), 'player_game_stats', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_game_stats_week'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_team'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_season'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    # ### end Alembic commands ###
