"""Add season and week to Game

Revision ID: f55ca88acbc1
Revises: 43b63420d188
Create Date: 2025-11-19 23:24:52.515481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55ca88acbc1'
down_revision = '43b63420d188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('week', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_week'), 'games', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_week'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_column('games', 'week')
    op.drop_column('games', 'season')
    # ### end Alembic commands ###
