"""add_red_zone_stats

Revision ID: f5ee7d8d9278
Revises: a17ee946a36f
Create Date: 2025-11-18 21:58:23.667156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ee7d8d9278'
down_revision = 'a17ee946a36f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game_stats', sa.Column('red_zone_pass_attempts', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('red_zone_rush_attempts', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('red_zone_targets', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('red_zone_passing_tds', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('red_zone_rushing_tds', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('red_zone_receiving_tds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game_stats', 'red_zone_receiving_tds')
    op.drop_column('player_game_stats', 'red_zone_rushing_tds')
    op.drop_column('player_game_stats', 'red_zone_passing_tds')
    op.drop_column('player_game_stats', 'red_zone_targets')
    op.drop_column('player_game_stats', 'red_zone_rush_attempts')
    op.drop_column('player_game_stats', 'red_zone_pass_attempts')
    # ### end Alembic commands ###
